# Structure must match the `AppConfig` type
backendUrl: https://ws.spraakbanken.gu.se/ws/mink/v3/
minkUrl: https://spraakbanken.gu.se/mink

auth:
  apiUrl: https://sp.spraakbanken.gu.se/auth/
  guiUrl: https://spraakbanken.gu.se/auth/
  logoutUrl: https://sp.spraakbanken.gu.se/Shibboleth.sso/Logout

types:
  corpus:
    explore:
      korp:
        url: https://spraakbanken.gu.se/korp
      strix:
        url: https://spraakbanken.gu.se/strix
  lexicon:
    karps:
      url: https://spraakbanken.gu.se/karp
  metadata: true

sharing: true

tools:
  metadataEditor: true
